apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-agile-healthcare-deploy
  labels:
    app: star-agile-healthcare
spec:
  replicas: 3
  selector:
    matchLabels:
      app: star-agile-healthcare
  template:
    metadata:
      labels:
        app: star-agile-healthcare
    spec:
      containers:
      - name: star-agile-healthcare-container
        image: chowthri/health-care:latest   # Placeholder to be replaced in Jenkins
        ports:
        - containerPort: 8082
        imagePullPolicy: Always                 # ✅ Important for always pulling the new image
---
apiVersion: v1
kind: Service
metadata:
  name: star-agile-healthcare-service
spec:
  selector:
    app: star-agile-healthcare
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
    nodePort: 30036
